{% set name = "distlib" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: e4b58818180336dc9c529bfb9a0b58728ffc09ad92027a3f30b7cd91e3458579

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python 2.7|>=3.6
  run:
    - python 2.7|>=3.6

test:
  imports:
    - distlib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/distlib/
  summary: Distribution utilities
  doc_url: https://pythonhosted.org/distlib/
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nicoddemus
