{% set name = "distlib" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 14bad2d9b04d3a36127ac97f30b12a19268f211063d8f8ee4f47108896e11b46

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python 2.7|>=3.6
    - setuptools >=44
    - wheel >=0.29
  run:
    - python 2.7|>=3.6

test:
  imports:
    - distlib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/distlib/
  summary: Distribution utilities
  doc_url: https://pythonhosted.org/distlib/
  dev_url: https://github.com/pypa/distlib
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nicoddemus
    - xylar
