{% set name = "distlib" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 106fef6dc37dd8c0e2c0a60d3fca3e77460a48907f335fa28420463a6f799736

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - distlib
    - distlib._backport
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/distlib/
  summary: Distribution utilities
  doc_url: https://pythonhosted.org/distlib/
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nicoddemus
